table inet deluge_killswitch {

  chain output {
    type filter hook output priority 0;

    # allow loopback
    oif lo accept

    # allow VPN tunnel only
    oifname "nordlynx" accept

    # block deluge user everywhere else
    meta skuid deluge drop
  }

  chain input {
    type filter hook input priority 0;

    iif lo accept
    iifname "nordlynx" accept

    meta skuid deluge drop
  }
}
