destroy table inet deluge_killswitch
table inet deluge_killswitch {

  chain output {
    type filter hook output priority 0;

    oif lo accept
    oifname "nordlynx" accept

    # allow WireGuard encrypted tunnel packets (NordVPN marks these)
    meta skuid deluge meta mark 0xe1f1 accept

    meta skuid deluge drop
  }
}
